### ISSUE TITLE
Links have font

### ISSUE THREAD

**Issue by marbaque** [ocwc/oeglobal#12]
I noticed all links inside `<article>` have serif font applied to it. I think it would be easier to handle if links don't have a font applied unless it is a very specific type of link such as buttons. I can do this change if you agree @gandalfar 

For example in https://www.oeglobal.org/resource/ the headings have serif instead of sans-serif

By the way, I am posting an issue here (weird). It may work to document changes too.

**Comment by gandalfar** [comment]
Go ahead :)
